import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { getTasks, completeTask } from "../services/api";
import type { Task } from "../types";
import { Card } from "../components/ui/Card";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Skeleton } from "../components/ui/Skeleton";
import { Modal } from "../components/ui/Modal";
import { 
  Table, 
  TableHeader, 
  TableBody, 
  TableRow, 
  TableHead, 
  TableCell 
} from "../components/ui/Table";
import { formatRelativeTime } from "../utils/formatters";
import { 
  AlertTriangle, 
  CheckCircle2, 
  ArrowUpRight,
  InboxIcon
} from "lucide-react";

// Simplified human-readable task type labels
const taskTypeLabel = (type: string) => {
  if (type === "ESCALATION") return "Escalation";
  if (type === "FOLLOW_UP") return "Follow Up";
  if (type === "ASSIGNMENT") return "Assignment";
  return type;
};

const taskTypeDescription = (type: string) => {
  if (type === "ESCALATION") return "This case has been stuck too long. Manager needs to step in.";
  if (type === "FOLLOW_UP") return "The assigned officer hasn't completed this case within the expected time.";
  if (type === "ASSIGNMENT") return "This case has no one working on it. An admin needs to assign it.";
  return "";
};

export default function Tasks() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<string>("OPEN");
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [completing, setCompleting] = useState(false);

  const loadTasks = async () => {
    try {
      const data = await getTasks();
      setTasks(data);
    } catch (err) {
      console.error("Failed to load tasks", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadTasks();
    const handleWorkflowRun = () => loadTasks();
    window.addEventListener('workflow-run-completed', handleWorkflowRun);
    return () => window.removeEventListener('workflow-run-completed', handleWorkflowRun);
  }, []);

  const handleComplete = async () => {
    if (!selectedTask) return;
    setCompleting(true);
    try {
      await completeTask(selectedTask.id);
      setSelectedTask(null);
      await loadTasks();
    } catch (err) {
      console.error(err);
    } finally {
      setCompleting(false);
    }
  };

  const openTasks = tasks.filter(t => t.status === "OPEN");
  const completedTasks = tasks.filter(t => t.status === "COMPLETED");
  const escalations = openTasks.filter(t => t.task_type === "ESCALATION");

  const filteredTasks = activeTab === "OPEN" ? openTasks : completedTasks;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 tracking-tight">Task Inbox</h2>
          <p className="text-sm text-slate-500 mt-0.5">
            To-dos and alerts automatically generated by the workflow engine.
          </p>
        </div>
        {escalations.length > 0 && (
          <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-rose-50 border border-rose-200 text-rose-700 text-xs font-bold">
            <AlertTriangle className="w-3.5 h-3.5 animate-pulse" />
            {escalations.length} urgent escalation{escalations.length > 1 ? 's' : ''}
          </span>
        )}
      </div>

      {/* Simple 2-tab Switch */}
      <div className="flex items-center gap-2">
        <button
          onClick={() => setActiveTab("OPEN")}
          className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
            activeTab === "OPEN" ? "bg-slate-900 text-white" : "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50"
          }`}
        >
          Open Tasks ({openTasks.length})
        </button>
        <button
          onClick={() => setActiveTab("COMPLETED")}
          className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
            activeTab === "COMPLETED" ? "bg-emerald-600 text-white" : "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50"
          }`}
        >
          Resolved ({completedTasks.length})
        </button>
      </div>

      {/* Task Table */}
      <Card>
        {loading ? (
          <div className="p-6 space-y-3">
            {[1, 2, 3, 4].map(i => <Skeleton key={i} className="h-14 w-full" />)}
          </div>
        ) : filteredTasks.length === 0 ? (
          <div className="py-16 text-center space-y-2">
            {activeTab === "OPEN" ? (
              <>
                <CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto" />
                <p className="text-sm font-medium text-slate-700">No open tasks</p>
                <p className="text-xs text-slate-400">
                  Run the workflow engine to check if any cases need attention.
                </p>
              </>
            ) : (
              <>
                <InboxIcon className="w-10 h-10 text-slate-300 mx-auto" />
                <p className="text-sm font-medium text-slate-700">No resolved tasks yet</p>
              </>
            )}
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Type</TableHead>
                <TableHead>What needs to happen</TableHead>
                <TableHead>Case</TableHead>
                <TableHead>Who</TableHead>
                <TableHead>When</TableHead>
                <TableHead className="text-right">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredTasks.map((task) => {
                const isEscalation = task.task_type === "ESCALATION";
                const isFollowUp = task.task_type === "FOLLOW_UP";
                const isDone = task.status === "COMPLETED";

                return (
                  <TableRow
                    key={task.id}
                    className={`transition-colors ${
                      isDone
                        ? "opacity-60 bg-slate-50/60"
                        : isEscalation
                        ? "bg-rose-50/40 hover:bg-rose-50/70 border-l-4 border-l-rose-400"
                        : isFollowUp
                        ? "bg-amber-50/20 hover:bg-amber-50/50"
                        : "hover:bg-slate-50"
                    }`}
                  >
                    {/* Type */}
                    <TableCell>
                      <div className="flex items-center gap-2">
                        {isEscalation && !isDone && (
                          <AlertTriangle className="w-4 h-4 text-rose-500 animate-pulse shrink-0" />
                        )}
                        <Badge
                          variant={isEscalation ? "error" : isFollowUp ? "warning" : "info"}
                          dot
                          pulse={isEscalation && !isDone}
                        >
                          {taskTypeLabel(task.task_type)}
                        </Badge>
                      </div>
                    </TableCell>

                    {/* What needs to happen */}
                    <TableCell>
                      <div className={`text-xs font-semibold ${isDone ? 'line-through text-slate-400' : 'text-slate-800'}`}>
                        {taskTypeDescription(task.task_type)}
                      </div>
                    </TableCell>

                    {/* Case */}
                    <TableCell>
                      <Link
                        to={`/applications/${task.application_id}`}
                        className="font-mono text-xs font-bold text-indigo-600 hover:text-indigo-800 hover:underline inline-flex items-center gap-1"
                      >
                        Case #{task.application_id}
                        <ArrowUpRight className="w-3 h-3 text-slate-400" />
                      </Link>
                    </TableCell>

                    {/* Who */}
                    <TableCell>
                      <div className="text-xs font-semibold text-slate-800">
                        {task.assigned_to?.name || task.assigned_to_role || "Admin"}
                      </div>
                      {task.assigned_to?.name && (
                        <div className="text-[10px] text-slate-500">{task.assigned_to_role}</div>
                      )}
                    </TableCell>

                    {/* When */}
                    <TableCell>
                      <div className="text-xs text-slate-600">
                        {formatRelativeTime(task.created_at)}
                      </div>
                    </TableCell>

                    {/* Action */}
                    <TableCell className="text-right">
                      {!isDone ? (
                        <Button
                          size="xs"
                          variant={isEscalation ? "danger" : "primary"}
                          onClick={() => setSelectedTask(task)}
                        >
                          Resolve
                        </Button>
                      ) : (
                        <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                          <CheckCircle2 className="w-3 h-3" />
                          Done
                        </span>
                      )}
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </Card>

      {/* Resolve Modal */}
      <Modal
        isOpen={!!selectedTask}
        onClose={() => setSelectedTask(null)}
        title="Mark Task as Resolved"
        description={`Confirming this means the issue for Case #${selectedTask?.application_id} has been handled.`}
        footer={
          <>
            <Button variant="ghost" size="sm" onClick={() => setSelectedTask(null)}>
              Cancel
            </Button>
            <Button
              variant={selectedTask?.task_type === 'ESCALATION' ? 'danger' : 'primary'}
              size="sm"
              onClick={handleComplete}
              loading={completing}
            >
              Mark as Resolved
            </Button>
          </>
        }
      >
        {selectedTask && (
          <div className="py-2 space-y-3">
            <div className={`p-4 rounded-2xl border ${
              selectedTask.task_type === 'ESCALATION'
                ? 'bg-rose-50 border-rose-200'
                : 'bg-slate-50 border-slate-200'
            }`}>
              <div className="flex items-center gap-2 mb-2">
                <Badge variant={selectedTask.task_type === 'ESCALATION' ? 'error' : 'info'} dot>
                  {taskTypeLabel(selectedTask.task_type)}
                </Badge>
              </div>
              <p className="text-sm text-slate-700">
                {taskTypeDescription(selectedTask.task_type)}
              </p>
              <p className="text-xs text-slate-500 mt-2">
                Assigned to: <strong>{selectedTask.assigned_to?.name || selectedTask.assigned_to_role || 'Admin'}</strong>
              </p>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
